#' Example LD Output for Autotetraploid Arabidopsis arenosa
#'
#' A subset of linkage disequilibrium estimation results generated by AutoLD.
#'
#' @format A data frame containing estimation results.
#' @source Simulated/Empirical subset
"arenosa_ld_example"
